// ============================================================================
// NPC chat thread storage — localStorage, versioned envelope, designed to
// carry forward into Phase 2's quest-scoped interactions.
//
// Storage key shape:
//   at.npc.v1.<characterKey>.<npcId>.<threadId>
//
//   characterKey = the bible's createdAt timestamp (stable, survives renames)
//   npcId        = stable id from NPC_CATALOG (or addon-supplied npc id later)
//   threadId     = 'default' in Phase 0; Phase 2 uses quest/gossip ids
//
// The `trigger` and `relationshipSummary` fields exist now so Phase 2 can
// start populating them without a schema migration.
// ============================================================================

import type { ChatMessage, CharacterBible } from '../types';

const SCHEMA_VERSION = 1;
const KEY_PREFIX = 'at.npc.v1';

export type ThreadTrigger = 'manual' | 'quest-detail' | 'gossip-show' | 'quest-turn-in';

export interface NpcThread {
  schemaVersion: number;
  characterKey: string;
  npcId: string;
  threadId: string;
  startedAt: number;
  updatedAt: number;
  trigger: ThreadTrigger;
  /**
   * Phase 1+: rolling summary of the relationship between this hero and NPC,
   * generated by a periodic summarization pass. Phase 0 leaves this unset.
   */
  relationshipSummary?: string;
  turns: ChatMessage[];
}

/** Returns a stable key for a given hero bible. */
export function characterKey(bible: Pick<CharacterBible, 'createdAt'>): string {
  return String(bible.createdAt);
}

function storageKey(charKey: string, npcId: string, threadId: string): string {
  return `${KEY_PREFIX}.${charKey}.${npcId}.${threadId}`;
}

/** Returns null if no thread exists or the saved blob is invalid. */
export function loadNpcThread(
  bible: Pick<CharacterBible, 'createdAt'>,
  npcId: string,
  threadId = 'default',
): NpcThread | null {
  try {
    const raw = localStorage.getItem(storageKey(characterKey(bible), npcId, threadId));
    if (!raw) return null;
    const parsed = JSON.parse(raw) as Partial<NpcThread>;
    if (!parsed || typeof parsed !== 'object') return null;
    if (parsed.schemaVersion !== SCHEMA_VERSION) {
      console.warn(
        `[npcChatStore] schemaVersion mismatch (got ${parsed.schemaVersion}, expected ${SCHEMA_VERSION})`,
      );
      return null;
    }
    if (!Array.isArray(parsed.turns)) return null;
    // Conservative: require fields we'll need.
    if (
      typeof parsed.characterKey !== 'string' ||
      typeof parsed.npcId !== 'string' ||
      typeof parsed.threadId !== 'string'
    ) {
      return null;
    }
    return parsed as NpcThread;
  } catch (err) {
    console.warn('[npcChatStore] failed to load thread:', err);
    return null;
  }
}

export function saveNpcThread(thread: NpcThread): void {
  const toSave: NpcThread = {
    ...thread,
    schemaVersion: SCHEMA_VERSION,
    updatedAt: Date.now(),
  };
  localStorage.setItem(
    storageKey(thread.characterKey, thread.npcId, thread.threadId),
    JSON.stringify(toSave),
  );
}

export function clearNpcThread(
  bible: Pick<CharacterBible, 'createdAt'>,
  npcId: string,
  threadId = 'default',
): void {
  localStorage.removeItem(storageKey(characterKey(bible), npcId, threadId));
}

export function newNpcThread(
  bible: Pick<CharacterBible, 'createdAt'>,
  npcId: string,
  opts: { threadId?: string; trigger?: ThreadTrigger } = {},
): NpcThread {
  const now = Date.now();
  return {
    schemaVersion: SCHEMA_VERSION,
    characterKey: characterKey(bible),
    npcId,
    threadId: opts.threadId ?? 'default',
    startedAt: now,
    updatedAt: now,
    trigger: opts.trigger ?? 'manual',
    turns: [],
  };
}

/**
 * How many recent turns to replay into the prompt. Once a relationshipSummary
 * starts being generated (Phase 1+), older turns can be safely dropped.
 */
export const REPLAY_TURN_LIMIT = 10;

export function trimForReplay(turns: ChatMessage[]): ChatMessage[] {
  if (turns.length <= REPLAY_TURN_LIMIT) return turns;
  return turns.slice(turns.length - REPLAY_TURN_LIMIT);
}
